name: borntoruncz
favicon: null
layout_spectrum: 0.6938314496073872
typography_spectrum: 0.19925875193439424
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.07532090856693685
  lightness: 0.3301017736084759
  saturation: 0.8174131475389004
  rhythmicContrast: 0.4069832465611398
purpose: []
