name: borntoruncz
favicon: null
layout_spectrum: 0.6938314496073872
typography_spectrum: 0.19925875193439424
title: Born To Run CZ/SK
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1f1f1f'
    - '#e00000'
    - '#626a73'
    - '#ef6f70'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
